#!/bin/bash
SSD=/dev/disk/by-id/ata-KINGSTON_RBU-SUS151S364GD_50026B7E51D74E12
KEY=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0

(
echo "$(tput setaf 6 & tput smso)Starting live ISO download . . .$(tput sgr0)"
wget http://mirrors.ocf.berkeley.edu/archlinux/iso/$(date +%Y).$(date +%m).01/archlinux-$(date +%Y).$(date +%m).01-dual.iso --output-document=/tmp/live.iso
mv -v /tmp/live.iso /mnt/boot
) &

echo "$(tput setaf 6 & tput smso)Creating new GPT tables . . .$(tput sgr0)"
parted -s $SSD mktable gpt
parted -s $SSD mkpart bios 34s 2047s
parted -s $SSD set 1 bios_grub on
parted -s $SSD mkpart boot 2048s 1000MiB
parted -s $SSD -- mkpart sys 1000MiB -34s
parted -s $KEY mktable gpt

echo "$(tput setaf 6 & tput smso)Generating keyfiles . . .$(tput sgr0)"
dd bs=1024 count=8 if=/dev/random of=boot iflag=fullblock
dd bs=1024 count=8 if=/dev/random of=sys iflag=fullblock

echo "$(tput setaf 6 & tput smso)Encrypting . . .$(tput sgr0)"
cryptsetup -v luksFormat $SSD-part2 boot --batch-mode
cryptsetup -v open --type luks $SSD-part2 boot --key-file=boot
cryptsetup -v luksFormat $SSD-part3 sys --batch-mode
cryptsetup -v open --type luks $SSD-part3 sys --key-file=sys

echo "$(tput setaf 6 & tput smso)Creating LVM . . .$(tput sgr0)"
vgcreate -v sys /dev/mapper/sys
lvcreate -v -l +100%FREE sys -n root

echo "$(tput setaf 6 & tput smso)Making filesystems . . .$(tput sgr0)"
mkfs.btrfs -L root -f /dev/mapper/sys-root
mkfs.btrfs -L boot -f /dev/mapper/boot

echo "$(tput setaf 6 & tput smso)Mounting filesystems . . .$(tput sgr0)"
mount -v /dev/mapper/sys-root /mnt
mkdir -v /mnt/boot
mount -v /dev/mapper/boot /mnt/boot

echo "$(tput setaf 6 & tput smso)Inserting keyfile . . .$(tput sgr0)"
cp -v boot /mnt/etc
shred -v boot -n 8 -z
cp -v sys /mnt/boot
shred -v sys -n 8 -z

echo "$(tput setaf 6 & tput smso)Generating fstab . . .$(tput sgr0)"
mkdir -v /mnt/etc
genfstab -U -p /mnt >> /mnt/etc/fstab
sed -i 's/relatime/noatime,discard,compress=lzo/g' /mnt/etc/fstab
mount -v -o remount /mnt
echo boot	$SSD-part2	/etc/boot >> /etc/crypttab

echo "$(tput setaf 6 & tput smso)Installing packages . . .$(tput sgr0)"
pacstrap /mnt base base-devel

echo "$(tput setaf 6 & tput smso)Starting next stage . . .$(tput sgr0)"
cp -v -r payload/. /mnt
arch-chroot /mnt ./chroot
