#!/bin/bash
SSD=/dev/disk/by-id/ata-KINGSTON_RBU-SUS151S364GD_50026B7E51D74E12
KEY=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0
BOOT=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0-part2

echo "$(tput setaf 6 & tput smso)Creating new GPT tables . . .$(tput sgr0)"
parted -s $SSD mktable gpt
parted -s $KEY mktable gpt \
	mkpart bios 34s 2047s \
	set 1 bios_grub on \
	mkpart boot 2048s 100% \

echo "$(tput setaf 6 & tput smso)Generating keyfiles . . .$(tput sgr0)"
dd bs=1024 count=8 if=/dev/random of=key iflag=fullblock
dd bs=1024 count=8 if=/dev/random of=sys iflag=fullblock

echo "$(tput setaf 6 & tput smso)Encrypting . . .$(tput sgr0)"
cryptsetup -v luksFormat $KEY-part2 key --batch-mode
cryptsetup -v open --type luks $KEY-part2 key --key-file=key
cryptsetup -v luksFormat $SSD sys --batch-mode
cryptsetup -v open --type luks $SSD sys --key-file=sys

echo "$(tput setaf 6 & tput smso)Creating LVM . . .$(tput sgr0)"
vgcreate -v sys /dev/mapper/sys
lvcreate -v -l +100%FREE sys -n root
vgcreate -v key /dev/mapper/key
lvcreate -v -l +100%FREE key -n boot

echo "$(tput setaf 6 & tput smso)Making filesystems . . .$(tput sgr0)"
mkfs.btrfs -L root -f /dev/mapper/sys-root
mkfs.btrfs -L boot -f /dev/mapper/key-boot

echo "$(tput setaf 6 & tput smso)Installing system. . .$(tput sgr0)"
mount -v /dev/mapper/sys-root /mnt -o compress=lzo
mkdir -v /mnt/boot
pacstrap /mnt base base-devel
genfstab -U -p /mnt >> /mnt/etc/fstab
sed -i 's/relatime/noatime,discard,compress=lzo/g' /mnt/etc/fstab
mount -v /dev/mapper/key-boot /mnt/boot -o compress=lzo

(
echo "$(tput setaf 6 & tput smso)Starting live ISO download . . .$(tput sgr0)"
wget http://mirrors.ocf.berkeley.edu/archlinux/iso/$(date +%Y).$(date +%m).01/archlinux-$(date +%Y).$(date +%m).01-dual.iso --output-document=/tmp/live.iso > /dev/null 2>&1
mv -v /tmp/live.iso /mnt/boot
) &

echo "$(tput setaf 6 & tput smso)Inserting keyfile . . .$(tput sgr0)"
cp -v key /mnt/etc
shred -v key -n 8 -z
cp -v sys /mnt/boot
shred -v sys -n 8 -z

echo "$(tput setaf 6 & tput smso)Starting next stage . . .$(tput sgr0)"
cp -v -r payload/. /mnt
arch-chroot /mnt ./chroot
