#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'live iso' {
	set iso='/live.iso'
	loopback loop $iso
	linux (loop)/arch/boot/x86_64/vmlinuz archisodevice=/dev/loop0 img_dev=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0-part3 img_loop=$iso
	initrd (loop)/arch/boot/x86_64/archiso.img
}
