#!/bin/bash
SSD=/dev/disk/by-id/ata-KINGSTON_RBU-SUS151S364GD_50026B7E51D74E12
SD=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0

echo "$(tput setaf 6 & tput smso)Installing packages . . .$(tput sgr0)"
pacman -R linux --noconfirm
pacman -Syyu connman wpa_supplicant wireless_tools\
	xorg-server xorg-server-utils xorg-xinit xorg-utils xorg-xkbcomp \
	xf86-input-synaptics xf86-video-intel mesa \
	alsa-utils acpi pulseaudio pulseaudio-alsa\
	wget git openssh \
	gptfdisk parted \
	zsh grml-zsh-config zsh-completions \
	vim \
	slock surf abs dmenu \
	gnupg xsel polkit grub dvtm btrfs-progs xbindkeys --noconfirm

echo "$(tput setaf 6 & tput smso)Configuring locale and time . . .$(tput sgr0)"
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8
ln -v -s /usr/share/zoneinfo/US/Pacific /etc/localtime
hwclock --systohc --utc

echo "$(tput setaf 6 & tput smso)Setting hostname and adding user . . .$(tput sgr0)"
echo pixel > /etc/hostname
useradd -m -g users -G wheel min

echo "$(tput setaf 6 & tput smso)Enable connman . . .$(tput sgr0)"
systemctl enable connman.service

echo "$(tput setaf 6 & tput smso)Set autologin . . .$(tput sgr0)"
mv -v /getty@tty1.service /etc/systemd/system/getty.target.wants

echo "$(tput setaf 6 & tput smso)Changing shells . . .$(tput sgr0)"
chsh -s /usr/bin/zsh root
chsh -s /usr/bin/zsh min

echo "$(tput setaf 6 & tput smso)Configuring vim . . .$(tput sgr0)"
echo 'export EDITOR=vim' >> /etc/profile
mv -v /vimrc /etc/vimrc
chown root:root /etc/vimrc

echo "$(tput setaf 6 & tput smso)Setting up sudo and su . . .$(tput sgr0)"
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
mv -v /su /etc/pam.d/su
chown root:root /etc/pam.d/su

echo "$(tput setaf 6 & tput smso)Editing logind . . .$(tput sgr0)"
mv -v /logind.conf /etc/systemd/logind.conf
chown root:root /etc/systemd/logind.conf

echo "$(tput setaf 6 & tput smso)Editing xorg.conf . . .$(tput sgr0)"
mv -v /10-keyboard.conf /etc/X11/xorg.conf.d/10-keyboard.conf
mv -v /10-monitor.conf /etc/X11/xorg.conf.d/10-monitor.conf
mv -v /20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf
mv -v /50-synaptics.conf /etc/X11/xorg.conf.d/50-synaptics.conf

echo "$(tput setaf 6 & tput smso)Configuring dmenu bin . . .$(tput sgr0)"
mv -v /dmenu_run /usr/local/bin
echo dmenu_run > /usr/local/bin/.exclude
touch /usr/local/sbin/.exclude
mv -v /xdrt /usr/local/bin
mv -v /T /usr/local/bin

echo "$(tput setaf 6 & tput smso)Starting next stage . . .$(tput sgr0)"
mv config.h /home/min/
rm chroot
su min -c ./user
