#!/bin/bash

SSD=/dev/disk/by-id/ata-KINGSTON_RBU-SUS151S364GD_50026B7E51D74E12
KEY=/dev/disk/by-id/usb-Generic_Power_Saving_USB_000000000260-0:0

echo "$(tput setaf 6 & tput smso)Installing yaourt . . .$(tput sgr0)"
mkdir ~/.builds
cd ~/.builds && wget https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz && tar -xzf package-query.tar.gz
cd ~/.builds && wget https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz && tar -xzf yaourt.tar.gz
cd ~/.builds/package-query && makepkg -si --noconfirm
cd ~/.builds/yaourt && makepkg -si --noconfirm
sudo sed -i 's/#AURURL/AURURL/' /etc/yaourtrc
sudo sed -i 's/aur/aur4/' /etc/yaourtrc

echo "$(tput setaf 6 & tput smso)Installing 4.1 samus kernel . . .$(tput sgr0)"
cd ~/.builds && git clone https://github.com/raphael/linux-4.1-samus
mv -v /.config ~/.builds/linux-4.1-samus/build/linux
cd linux-4.1-samus/build/linux
make -j4
sudo make modules_install
sudo make install
sudo pacman -R linux linux-headers
sudo mv -v /boot/vmlinuz-linux-samus4 /boot/vmlinuz-linux
sudo mv -v /boot/initramfs-linux-samus4.img /boot/initramfs-linux.img

echo "$(tput setaf 6 & tput smso)Installing dwm and st. . .$(tput sgr0)"
cd ~/.builds && sudo abs community/dwm
cp -v -r /var/abs/community/dwm ~/.builds/dwm
sudo chown min:users ~/config.h
cd ~/.builds/dwm && makepkg -si --noconfirm
mv -v ~/config.h ~/.builds/dwm/config.h
cp -v ~/.builds/dwm/config.h ~/.builds/dwm/src/config.h
cd ~/.builds/dwm && makepkg -efi --skipinteg --noconfirm
mkdir ~/.builds/st
sudo mv /PKGBUILD ~/.builds/st
sudo chown min:users ~/.builds/st/PKGBUILD
cd ~/.builds/st && makepkg --si --skipinteg --noconfirm

#echo "$(tput setaf 6 & tput smso)Installing drive . . .$(tput sgr0)"
#export GOPATH=~/.builds/gopath && go get -u github.com/odeke-em/drive/cmd/drive
#sudo cp ~/.builds/gopath/bin/drive /usr/bin

echo "$(tput setaf 6 & tput smso)Editing xinitrc . . .$(tput sgr0)"
sudo mv -v /.xinitrc ~/.xinitrc
sudo chown min:users ~/.xinitrc

echo "$(tput setaf 6 & tput smso)Setting up X autostart . . .$(tput sgr0)"
sudo mv -v /.zlogin ~/.zlogin
sudo chown min:users ~/.zlogin
touch ~/.hushlogin

echo "$(tput setaf 6 & tput smso)Finishing up . .$(tput sgr0)"
sudo cryptsetup luksAddKey $SSD-part2 --key-file=/etc/boot
sudo passwd
sudo passwd min
sudo mv -v /finish ~/finish
sudo chown min:users ~/finish
sudo rm /user
